# Generated by Django 6.0.1 on 2026-01-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_rename_created_at_payment_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
