# Generated by Django 6.0.1 on 2026-01-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_registration_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='OLD_PAYMENT', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(default='OLD_PAYMENT', max_length=20),
            preserve_default=False,
        ),
    ]
